project_name: lens
version: 2
builds:
  - main: ./cmd/lens
    id: "lens"
    binary: lens
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    goarm:
      - 6
      - 7
  - main: ./cmd/obstructionMapVideo
    id: "obstructionMapVideo"
    binary: obstructionMapVideo
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    goarm:
      - 6
      - 7

# https://goreleaser.com/customization/nfpm/
nfpms:
  - maintainer: clarkzjw <i@jinwei.me>
    description: LENS client to collect Starlink network measurement results
    homepage: https://github.com/clarkzjw/starlink-lens
    license: MIT
    package_name: lens
    dependencies:
    - bash
    - coreutils
    - iputils-ping
    - mtr
    - curl
    - traceroute
    - sudo
    - iproute2
    - dnsutils
    replaces:
    - inetutils-ping
    - mtr-tiny
    suggests:
    - ffmpeg
    - zstd
    formats:
    - deb
    priority: extra
    contents:
    - src: ./etc/systemd/lens.service
      dst: /lib/systemd/system/lens.service
      file_info:
        mode: 0644

dockers:
  - image_templates:
      - "docker.io/clarkzjw/lens"
    skip_push: true
